export const NAV_LINKS = [
  { label: 'About', href: '#about' },
  { label: 'Menu', href: '#menu' },
  { label: 'Chef', href: '#chef' },
  { label: 'Gallery', href: '#gallery' },
  { label: 'Reviews', href: '#reviews' },
  { label: 'Reservations', href: '#reservations' },
]

export const CONTACT_INFO = {
  address: '14 Mediterranean Quarter, Harbour Street, Dublin 2, Ireland',
  phone: '+353 1 555 0198',
  email: 'reservations@liora.ie',
  mapEmbedUrl:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2381.9!2d-6.2603!3d53.3498!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNTPCsDIwJzU5LjMiTiA2wrAxNSczNy4wIlc!5e0!3m2!1sen!2sie!4v1700000000000',
}

export const OPENING_HOURS = [
  { days: 'Monday – Thursday', hours: '12:00 – 23:00' },
  { days: 'Friday – Saturday', hours: '11:00 – 00:00' },
  { days: 'Sunday', hours: '12:00 – 22:00' },
]

export const RESERVATION_TIMES = [
  '12:00', '12:30', '13:00', '13:30', '14:00', '14:30',
  '15:00', '17:00', '17:30', '18:00', '18:30', '19:00',
  '19:30', '20:00', '20:30', '21:00', '21:30', '22:00',
]

export const SIGNATURE_DISHES = [
  {
    id: 'liora-mixed-grill',
    name: 'Liora Mixed Grill',
    price: '€52.90',
    description: 'Our signature sharing platter — Chicken Shish, Shish Kebab, Lamb Ribs and your choice of side.',
    image: '/images/dishes/turkish-mixed-grill-platter.jpeg',
    stars: 3,
    category: 'Charcoal Grill',
    for: '2 Persons',
  },
  {
    id: 'burrata-pizza',
    name: 'Burrata Pizza',
    price: '€15.90',
    description: 'Fresh burrata on tomato sauce with cherry tomatoes, basil oil, and cracked black pepper.',
    image: '/images/dishes/burrata-pizza.jpeg',
    stars: 2,
    category: 'Handcrafted Pizza',
  },
  {
    id: 'beef-tenderloin-shish',
    name: 'Beef Tenderloin Shish',
    price: '€17.90',
    description: 'Premium beef tenderloin, hand-cut and skewered, charcoal-grilled to your desired temperature.',
    image: '/images/dishes/grilled-beef-skewer.jpeg',
    stars: 2,
    category: 'Charcoal Grill',
  },
  {
    id: 'lamb-chops',
    name: 'Lamb Chops',
    price: '€23.90',
    description: 'Tender lamb chops marinated in herbs, seared over high-heat charcoal flames.',
    image: '/images/dishes/grilled-lamb-chops.jpeg',
    stars: 2,
    category: 'Charcoal Grill',
  },
  {
    id: 'grilled-salmon',
    name: 'Grilled Salmon',
    price: '€21.90',
    description: 'Fresh Atlantic salmon fillet char-grilled and served with Mediterranean herbs.',
    image: '/images/dishes/mediterranian-grilled-salmon.jpeg',
    stars: 2,
    category: 'Charcoal Grill',
  },
  {
    id: 'the-boss-double',
    name: 'The Boss Double',
    price: '€19.90',
    description: 'Two charcoal-grilled beef patties, double cheese, crispy onions, and our secret boss sauce.',
    image: '/images/dishes/double-beef-burger.jpeg',
    stars: 2,
    category: 'Charcoal Grill Burger',
  },
  {
    id: 'liora-pizza',
    name: 'Liora Pizza',
    price: '€15.90',
    description: 'Our signature chef-curated combination of the finest Mediterranean ingredients.',
    image: '/images/dishes/mediterranian-pizza.jpeg',
    stars: 2,
    category: 'Handcrafted Pizza',
  },
  {
    id: 'meze-plate',
    name: 'Meze Plate',
    price: '€19.90',
    description: 'A generous selection of our finest mezze — hummus, baba ghanoush, dolma, cacik, and fresh bread.',
    image: '/images/dishes/meze-platter.jpeg',
    stars: 2,
    category: 'Starters',
  },
  {
    id: 'hot-honey-pepperoni',
    name: 'Hot Honey Pepperoni',
    price: '€14.90',
    description: 'Premium pepperoni, mozzarella, and a drizzle of hot honey to finish.',
    image: '/images/dishes/hot-honey-pepperoni-pizza.jpeg',
    stars: 2,
    category: 'Handcrafted Pizza',
  },
  {
    id: 'monterey-jack',
    name: 'Monterey Jack',
    price: '€17.90',
    description: 'Beef patty with Monterey Jack cheese, guacamole, jalapeños, and chipotle mayo.',
    image: '/images/dishes/gourmet-burger.jpeg',
    stars: 2,
    category: 'Charcoal Grill Burger',
  },
  {
    id: 'baklava-ice-cream',
    name: 'Baklava & Ice Cream',
    price: '€7.90',
    description: 'Honey-soaked baklava with crushed pistachios paired with premium vanilla ice cream.',
    image: '/images/dishes/baklava-with-icecream.jpeg',
    stars: 2,
    category: 'Desserts',
  },
  {
    id: 'liora-mocktail',
    name: 'Liora Mocktail',
    price: '€5.90',
    description: 'A refreshing blend of seasonal fruits, botanicals, and sparkling water.',
    image: '/images/dishes/mocktail.jpeg',
    stars: 2,
    category: 'Drinks',
  },
  {
    id: 'adana-kebab',
    name: 'Adana Kebab',
    price: '€14.90',
    description: 'Spiced minced lamb on flat skewers, grilled over charcoal — a Turkish street-food classic elevated.',
    image: '/images/dishes/adana-kebab.jpeg',
    stars: 2,
    category: 'Charcoal Grill',
  },
  {
    id: 'lamb-ribs',
    name: 'Lamb Ribs',
    price: '€19.90',
    description: 'Fall-off-the-bone lamb ribs slow-cooked then finished over charcoal for a caramelised crust.',
    image: '/images/dishes/lamb-ribs.jpeg',
    stars: 2,
    category: 'Charcoal Grill',
  },
  {
    id: 'doner-plate',
    name: 'Döner Plate',
    price: '€13.90',
    description: 'Sliced döner meat on a plate with fresh salad, rice, and house sauces.',
    image: '/images/dishes/doner-plate.jpeg',
    stars: 2,
    category: 'Döner',
  },
  {
    id: 'greek-salad',
    name: 'Greek Salad',
    price: '€13.90',
    description: 'Ripe tomatoes, cucumber, Kalamata olives, red onion, and a generous slab of feta in olive oil.',
    image: '/images/dishes/greek-salad.jpeg',
    stars: 2,
    category: 'Salads',
  },
  {
    id: 'bresaola-pizza',
    name: 'Bresaola Pizza',
    price: '€15.90',
    description: 'Air-dried bresaola, rocket, shaved parmesan, and truffle oil on a thin crispy base.',
    image: '/images/dishes/bresaola-pizza.jpeg',
    stars: 2,
    category: 'Handcrafted Pizza',
  },
  {
    id: 'mud-cake',
    name: 'Mud Cake',
    price: '€7.90',
    description: 'Rich dense chocolate mud cake served warm with cream.',
    image: '/images/dishes/mud-cake.jpeg',
    stars: 2,
    category: 'Desserts',
  },
]
